import os
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
SPOTIPY_CLIENT_ID = os.getenv('SPOTIPY_CLIENT_ID')
SPOTIPY_CLIENT_SECRET = os.getenv('SPOTIPY_CLIENT_SECRET')
GCS_ENGINE_ID = os.getenv("GCS_ENGINE_ID")
GCS_API_KEY = os.getenv("GCS_API_KEY")
MUSICXMATCH_API_KEY = os.getenv("MUSICXMATCH_API_KEY")
